spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/auth/**
            - id: grade-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/grade/**
            - id: student-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/student/**
            - id: teacher-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/teacher/**

          discovery:
            locator:
              enabled: false